django_test/djtem/src/blog/urls.py
from django.conf.urls import url


from .views import (
    post_model_create_view,
    post_model_detail_view,
    post_model_delete_view,
    post_model_list_view,
    post_model_update_view,
    some_test_view,
    home,
    intemplate,
    )

urlpatterns = [
    url(r'^$', post_model_list_view, name='list'),
    url(r'^test/$', some_test_view),
    url(r'^create/$', post_model_create_view, name='create'),
    url(r'^(?P<id>\d+)/$', post_model_detail_view, name='detail'),
    url(r'^(?P<id>\d+)/delete/$', post_model_delete_view, name='delete'),
    url(r'^(?P<id>\d+)/edit/$', post_model_update_view, name='update'),
    #url(r'^admin/', admin.site.urls),
    #url(r'^$', home, name='home'),
    #url(r'^redirect/$', redirect_somewhere, name='home')
]

# translations

urlpatterns = [
    url(r'^home/$', home),
    url(r'^intemplate/$', intemplate),
]

django_test/djtem/src/djtem/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog'))
]

django_test/djtem/src/blog/models.py
from datetime import timedelta, datetime, date

from django.db import models
from django.db.models.signals import pre_save, post_save
from django.utils.encoding import smart_text
from django.utils import timezone 
from django.utils.text import slugify
from django.utils.timesince import timesince


# Create your models here.


#from .validators import validate_author_email, validate_justin

PUBLISH_CHOICES = [
        ('draft', 'Draft'),
        ('publish', 'Publish'),
        ('private', 'Private'),
    ]

class PostModelQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)

    def post_title_items(self, value):
        return self.filter(title__icontains=value)


class PostModelManager(models.Manager):
    def get_queryset(self):
        return PostModelQuerySet(self.model, using=self._db)

    def all(self, *args, **kwargs):
        #qs = super(PostModelManager, self).all(*args, **kwargs).active() #.filter(active=True)
        #print(qs)
        qs = self.get_queryset().active()
        return qs

    def get_timeframe(self, date1, date2):
        #assume datetime objects
        qs = self.get_queryset()
        qs_time_1 = qs.filter(publish_date__gte=date1)
        qs_time_2 = qs_time_1.filter(publish_date__lt=date2) # Q Lookups
        #final_qs = (qs_time_1 | qs_time_2).distinct()
        return qs_time_2

class PostModel(models.Model):
    id              = models.BigAutoField(primary_key=True)
    active          = models.BooleanField(default=True) #empty in the database
    title           = models.CharField(
                            max_length=240, 
                            verbose_name='Post title', 
                            unique=True,
                            error_messages={
                                "unique": "This title is not unique, please try again.",
                                "blank": "This field is not full, please try again."
                            },
                            help_text='Must be a unique title.')
    slug            = models.SlugField(null=True, blank=True)
    content         = models.TextField(null=True, blank=True)
    publish         = models.CharField(max_length=120, choices=PUBLISH_CHOICES, default='draft')
    view_count      = models.IntegerField(default=0)
    publish_date    = models.DateField(auto_now=False, auto_now_add=False, default=timezone.now)
    author_email    = models.EmailField(max_length=240, null=True, blank=True)
    updated         = models.DateTimeField(auto_now=True)
    timestamp       = models.DateTimeField(auto_now_add=True)

    objects = PostModelManager()
    other = PostModelManager()
    #save = PostModelManager()

    def save(self, *args, **kwargs):
        # if not self.slug and self.title:
        #     self.slug = slugify(self.title)
        super(PostModel, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        #unique_together = [('title', 'slug')]

    def __unicode__(self): #python 2
        return smart_text(self.title) #self.title

    def __str__(self): #python 3
        return smart_text(self.title)

    @property
    def age(self):
        if self.publish == 'publish':
            now = datetime.now()
            publish_time = datetime.combine(
                                self.publish_date,
                                datetime.now().min.time()
                        )
            try:
                difference = now - publish_time
            except:
                return "Unknown"
            if difference <= timedelta(minutes=1):
                return 'just now'
            return '{time} ago'.format(time= timesince(publish_time).split(', ')[0])
        return "Not published"



def blog_post_model_pre_save_receiver(sender, instance, *args, **kwargs):
    print("before save")
    if not instance.slug and instance.title:
        instance.slug = slugify(instance.title) 

pre_save.connect(blog_post_model_pre_save_receiver, sender=PostModel)



def blog_post_model_post_save_receiver(sender, instance, created, *args, **kwargs):
    print("after save")
    print(created)
    if created:
        if not instance.slug and instance.title:
            instance.slug = slugify(instance.title)
            instance.save()

post_save.connect(blog_post_model_post_save_receiver, sender=PostModel)







'''
python manage.py makemigrations #every time you change models.py
python manage.py migate


ModelForm
forms.CharField(max_length=120, choices=PUBLISH_CHOICES, default='draft')

'''

django_test/djtem/src/blog/forms.py
from django import forms


from .models import PostModel


class PostModelForm(forms.ModelForm):
    class Meta:
        model = PostModel
        fields = [
            'title',
            'content'
        ]

django_test/djtem/src/blog/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.

from .forms import PostModelForm
from .models import PostModel



def some_test_view(request):
    some_list = ['abc', 123, 'item4', 'another']
    context = {
        "viewTitle" : "This Is AWesome",
        "abc" : 300,
        "addNum" : 300,
        "today" : datetime.datetime.now().today(),
        'object_list' : some_list,
    }
    template = 'blog/test-view3.html'
    return render(request, template, context)

#@login_required
def post_model_create_view(request):
    form = PostModelForm(request.POST or None)
    context = {
        "form": form
    }
    if form.is_valid():
        obj = form.save(commit=False)
        #print(obj.title)
        obj.save()
        messages.success(request, "Created a new blog post!")
        context = {
            "form": PostModelForm()
        }
        #return HttpResponseRedirect("/blog/{num}".format(num=obj.id))
    
    template = "blog/create-view.html"
    return render(request, template, context)

#@login_required
def post_model_update_view(request, id=None):
    obj = get_object_or_404(PostModel, id=id)
    form = PostModelForm(request.POST or None, instance=obj)
    context = {
        "form": form
    }
    if form.is_valid():
        obj = form.save(commit=False)
        #print(obj.title)
        obj.save()
        messages.success(request, "Updated post!")
        return HttpResponseRedirect("/blog/{num}".format(num=obj.id))
    
    template = "blog/update-view.html"
    return render(request, template, context)


def post_model_detail_view(request, id=None):
    obj = get_object_or_404(PostModel, id=id)
    context = {
        "instance": obj,
    }
    template = "blog/detail-view.html"
    return render(request, template, context)



def post_model_delete_view(request, id=None):
    obj = get_object_or_404(PostModel, id=id)
    if request.method == "POST":
        obj.delete()
        messages.success(request, "Post deleted")
        return HttpResponseRedirect("/blog/")
    context = {
        "object": obj,
    }
    template = "blog/delete-view.html"
    return render(request, template, context)


def post_model_list_view(request):
    #query = request.GET["q"]
    query = request.GET.get("q", None)
    qs = PostModel.objects.all()
    for item in qs:
        print(item.title)
    if query is not None:
        qs = qs.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(slug__icontains=query)
                )
    context = {
        "object_list": qs,
    }
    template = "blog/list-view.html"
    return render(request, template, context)



@login_required(login_url='/login/')
def login_required_view(request):
    print(request.user)
    qs = PostModel.objects.all()
    context = {
        "object_list": qs,
    }

    if request.user.is_authenticated():
        template = "blog/list-view.html"
    else:
        template = "blog/list-view-public.html"
        #raise Http404
        return HttpResponseRedirect("/login")
    
    return render(request, template, context)




def post_model_robust_view(request, id=None):
    obj = None
    context =  {}
    success_message = 'A new post was created'
    
    if id is None:
        "obj is could be created"
        template = "blog/create-view.html"
    else:
        "obj prob exists"
        obj = get_object_or_404(PostModel, id=id)
        success_message = 'A new post was created'
        context["object"] = obj
        template = "blog/detail-view.html"
        if "edit" in request.get_full_path():
            template = "blog/update-view.html"
        if "delete" in request.get_full_path():
            template = "blog/delete-view.html"
            if request.method == "POST":
                obj.delete()
                messages.success(request, "Post deleted")
                return HttpResponseRedirect("/blog/")

    #if "edit" in request.get_full_path() or "create" in request.get_full_path():
    form = PostModelForm(request.POST or None, instance=obj)
    context["form"] = form
    if form.is_valid():
        obj = form.save(commit=False)
        obj.save()
        messages.success(request, success_message)
        if obj is not None:
            return HttpResponseRedirect("/blog/{num}".format(obj.id))
        context["form"] - PostModelForm()
    return render(request, template, context)

from django.utils import translation
from django.utils.translation import ugettext as _
from django.http import HttpResponse

def my_view(request):
    output = _("Welcome to my site.")
    return HttpResponse(output)

def home(request):
    if 'lang' in request.GET:
        translation.activate(request.GET.get('lang'))

    title = _('Sign Up')
    return HttpResponse(title)

def intemplate(request):
    if 'lang' in request.GET:
        translation.activate(request.GET.get('lang'))
    return render(request, "myi18n.html")

django_test/djtem/src/blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %} My Project Title {% endblock title %}</title>
	<style>
		.bold {
			font-weight: bold;
		}
	</style>

</head>
<body>

{% include "blog/components/base-messages.html" %}
{% include "blog/components/search.html" %}


{% block content %} {% endblock content %}
</body>
</html>

django_test/djtem/src/blog/templates/blog/create-view.html
{% extends "blog/base.html" %}

{% block title %}
	Create new Post | {{ block.super }}
{% endblock title %}

{% block content %}
	<h1>Create new Post</h1>

	<form method='POST' action='.'>{% csrf_token %}
	{{ form.as_p }}

	<input type='submit' value='Create'>
	</form>
{% endblock content %}

django_test/djtem/src/blog/templates/blog/delete-view.html
<h1>Delete {{ object.title }}?</h1>


<form method='POST' action="."> {% csrf_token %}
Are you sure you want to delete this post?

<input type='submit' value='Yes'>

<a href='/blog/{{ object.id }}/'>Cancel</a>

</form>

django_test/djtem/src/blog/templates/blog/detail-view.html
{% extends "blog/base.html" %}

{% block content %}
	{% include "blog/components/object-detail.html" with object=instance %}
{% endblock content %}

django_test/djtem/src/blog/templates/blog/list-view-public.html
<h1>Hello there!</h1>

django_test/djtem/src/blog/templates/blog/list-view.html
{% extends "blog/base.html" %}

{% block title %}
	Blog List View | {{ block.super}}
{% endblock title %}

{% block content %}


	<h1>Hello World</h1>
	<hr>

	{% for object in object_list %}
		{% include "blog/components/object-detail.html" with object=object list_view=True %}
	<!-- <li>
	    <br>

	    <a href='{% url "blog:detail" id=object.id %}'>{{ object.title }}</a>
	    <a href='{{ object.get_absolute_url }}'>{{ object.title }}</a>
	</li> -->
	{% endfor %}

<!-- 
	{{ array_list }}

	{{ num }}

	{{ boolean_value }} -->

{% endblock content %}

django_test/djtem/src/blog/templates/blog/test-view.html
<h1>{{ viewTitle | title }}</h1>
<h1>{{ viewTitle | lower }}</h1>

<h1>{{ abc | add:addNum }}</h1>

{{ today|date:"D d M Y f a" }}


<ul>
	{% for obj in object_list %}
		{% for obj in object_list %}
			<li class="{% cycle "" "" "" "" "bold" %}">{{ forloop.counter }} {{ obj }}</li>
		{% endfor %} 
	{% endfor %} 
</ul>

<ul>
	{% for obj in object_list %}
		<li {% if forloop.counter|add:1|divisibleby:2 %}style="font-weight:bold;" {% endif %}>{{forloop.counter}} {% if forloop.first %} FIRST ITEM {% endif %}  {{ obj }}</li>
	{% endfor %}
</ul>


<ul>
	{% for obj in object_list %}
		<li {% if forloop.first %}style="font-weight:bold;" {% endif %}>{{forloop.counter}} {% if forloop.first %} FIRST ITEM {% endif %}  {{ obj }}</li>
	{% endfor %}
</ul>

django_test/djtem/src/blog/templates/blog/update-view.html
{% extends "blog/base.html" %}

{% block content %}
	<h1>Update {{ object.title }}</h1>

	{{ form.instance.title }}

	<form method='POST' action='.'>{% csrf_token %}
	{{ form.as_p }}

	<input type='submit' value='Create'>
	</form>
{% endblock content %}